server:
  port: 8085
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5632/postgres_meow
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true